server:
  port: 9443
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE:file:./certs/localhost.p12}
    key-store-type: PKCS12
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-alias: localhost
spring:
  application:
    name: human-being-service
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s409295
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
